// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUlufUZb-RSw8uHGVO8gn9aYCH5IwExeo',
    appId: '1:806179102751:web:490ea1dc08454a307f352a',
    messagingSenderId: '806179102751',
    projectId: 'jash-cd9d1',
    authDomain: 'jash-cd9d1.firebaseapp.com',
    storageBucket: 'jash-cd9d1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCh_Y5O01_tgTull1CqNEcwGtmd6N1f3cc',
    appId: '1:806179102751:android:dd3e1c811bc5207a7f352a',
    messagingSenderId: '806179102751',
    projectId: 'jash-cd9d1',
    storageBucket: 'jash-cd9d1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeQ76GQ8wCZjTzQkYxxsRLfE1TLskFpmk',
    appId: '1:806179102751:ios:feda2febd75943e57f352a',
    messagingSenderId: '806179102751',
    projectId: 'jash-cd9d1',
    storageBucket: 'jash-cd9d1.appspot.com',
    iosBundleId: 'com.example.jash',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeQ76GQ8wCZjTzQkYxxsRLfE1TLskFpmk',
    appId: '1:806179102751:ios:888988333a4763587f352a',
    messagingSenderId: '806179102751',
    projectId: 'jash-cd9d1',
    storageBucket: 'jash-cd9d1.appspot.com',
    iosBundleId: 'com.example.jash.RunnerTests',
  );
}
